//
// Generated file, do not edit! Created by opp_msgtool 6.0 from Packet.msg.
//

#ifndef __PACKET_M_H
#define __PACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class TcpIpPacket;
/**
 * Class generated from <tt>Packet.msg:15</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * packet TcpIpPacket
 * {
 *     int appHeader = 0;
 *     int tcpHeader = 0;
 *     int ipHeader = 0;
 *     int dllHeader = 0;
 *     int phyHeader = 0;
 *     int crc = 0;
 *     int data = 0;
 *     string packetFormat = NULL;
 * }
 * </pre>
 */
class TcpIpPacket : public ::omnetpp::cPacket
{
  protected:
    int appHeader = 0;
    int tcpHeader = 0;
    int ipHeader = 0;
    int dllHeader = 0;
    int phyHeader = 0;
    int crc = 0;
    int data = 0;
    omnetpp::opp_string packetFormat = NULL;

  private:
    void copy(const TcpIpPacket& other);

  protected:
    bool operator==(const TcpIpPacket&) = delete;

  public:
    TcpIpPacket(const char *name=nullptr, short kind=0);
    TcpIpPacket(const TcpIpPacket& other);
    virtual ~TcpIpPacket();
    TcpIpPacket& operator=(const TcpIpPacket& other);
    virtual TcpIpPacket *dup() const override {return new TcpIpPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getAppHeader() const;
    virtual void setAppHeader(int appHeader);

    virtual int getTcpHeader() const;
    virtual void setTcpHeader(int tcpHeader);

    virtual int getIpHeader() const;
    virtual void setIpHeader(int ipHeader);

    virtual int getDllHeader() const;
    virtual void setDllHeader(int dllHeader);

    virtual int getPhyHeader() const;
    virtual void setPhyHeader(int phyHeader);

    virtual int getCrc() const;
    virtual void setCrc(int crc);

    virtual int getData() const;
    virtual void setData(int data);

    virtual const char * getPacketFormat() const;
    virtual void setPacketFormat(const char * packetFormat);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TcpIpPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TcpIpPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline TcpIpPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<TcpIpPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PACKET_M_H

